from fastapi import FastAPI
from tools_agents.sql_agent import SQLAgent
import asyncio


app = FastAPI()
SQLAgent = SQLAgent()



@app.get("/conversational_agent_ret_sql")
"""
Endpoint to retrieve SQL query generated by the conversational agent based on the provided prompt and optional message history.
Args:
    prompt (str): The user's input prompt for the conversational agent.
    history_messages (list, optional): A list of previous conversation messages to provide context. Defaults to None.
Returns:
    dict: The data returned by the SQLAgent's conversational_agent_ret_sql method, typically containing the generated SQL query and related information.
"""
async def read_item(prompt: str, history_messages: list = None):
    data = SQLAgent.conversational_agent_ret_sql(prompt, history_messages)

    return data